services:
  sftp:
    image: atmoz/sftp
    ports:
      - "2223:22"
    volumes:
      - ./upload:/home/uptc-fit-sftp/upload
    command: uptc-fit-sftp:dcdl:1001
    networks:
      - backend

  node-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV:-development}
    ports:
      - "7011:3000"
    volumes:
      - ./:/usr/src/app
      - ./upload:/usr/src/app/upload
    depends_on:
      - sftp
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    networks:
      - backend

networks:
  backend:
    name: inscription-uptc-fit-network
    external: true
